use bevy::prelude::*;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Continent {
    Africa,
    Asia,
    Europe,
    NorthAmerica,
    SouthAmerica,
    Oceania,
}

#[derive(Clone, Debug)]
pub struct Country {
    pub id: u16,
    pub name: String,
    pub continent: Continent,
    pub initial_farming_capacity: f32,
    pub map_position: Vec2,
}

#[derive(Resource)]
pub struct CountryDatabase {
    pub countries: Vec<Country>,
}

impl CountryDatabase {
    pub fn new() -> Self {
        let countries = vec![
            // Africa
            Country {
                id: 1,
                name: "Algeria".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-500.0, 250.0),
            },
            Country {
                id: 2,
                name: "Angola".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-400.0, 100.0),
            },
            Country {
                id: 3,
                name: "Benin".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-350.0, 200.0),
            },
            Country {
                id: 4,
                name: "Botswana".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-400.0, -50.0),
            },
            Country {
                id: 5,
                name: "Burkina Faso".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-400.0, 200.0),
            },
            Country {
                id: 6,
                name: "Burundi".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-300.0, -100.0),
            },
            Country {
                id: 7,
                name: "Cameroon".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-350.0, 50.0),
            },
            Country {
                id: 8,
                name: "Cape Verde".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-550.0, 250.0),
            },
            Country {
                id: 9,
                name: "Central African Republic".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-300.0, 100.0),
            },
            Country {
                id: 10,
                name: "Chad".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-350.0, 150.0),
            },
            Country {
                id: 11,
                name: "Comoros".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-200.0, -200.0),
            },
            Country {
                id: 12,
                name: "Congo".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-300.0, 0.0),
            },
            Country {
                id: 13,
                name: "Democratic Republic of the Congo".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-250.0, -50.0),
            },
            Country {
                id: 14,
                name: "Djibouti".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-100.0, 200.0),
            },
            Country {
                id: 15,
                name: "Egypt".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-300.0, 300.0),
            },
            Country {
                id: 16,
                name: "Equatorial Guinea".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-350.0, 0.0),
            },
            Country {
                id: 17,
                name: "Eritrea".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-100.0, 250.0),
            },
            Country {
                id: 18,
                name: "Eswatini".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-300.0, -150.0),
            },
            Country {
                id: 19,
                name: "Ethiopia".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-150.0, 200.0),
            },
            Country {
                id: 20,
                name: "Gabon".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-350.0, -50.0),
            },
            Country {
                id: 21,
                name: "Gambia".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-500.0, 200.0),
            },
            Country {
                id: 22,
                name: "Ghana".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-400.0, 200.0),
            },
            Country {
                id: 23,
                name: "Guinea".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-450.0, 200.0),
            },
            Country {
                id: 24,
                name: "Guinea-Bissau".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-500.0, 200.0),
            },
            Country {
                id: 25,
                name: "Ivory Coast".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-450.0, 200.0),
            },
            Country {
                id: 26,
                name: "Kenya".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-150.0, -50.0),
            },
            Country {
                id: 27,
                name: "Lesotho".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-250.0, -200.0),
            },
            Country {
                id: 28,
                name: "Liberia".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-500.0, 200.0),
            },
            Country {
                id: 29,
                name: "Libya".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-400.0, 300.0),
            },
            Country {
                id: 30,
                name: "Madagascar".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-100.0, -200.0),
            },
            Country {
                id: 31,
                name: "Malawi".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-200.0, -150.0),
            },
            Country {
                id: 32,
                name: "Mali".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-450.0, 250.0),
            },
            Country {
                id: 33,
                name: "Mauritania".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-500.0, 280.0),
            },
            Country {
                id: 34,
                name: "Mauritius".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-150.0, -250.0),
            },
            Country {
                id: 35,
                name: "Morocco".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-500.0, 300.0),
            },
            Country {
                id: 36,
                name: "Mozambique".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-200.0, -100.0),
            },
            Country {
                id: 37,
                name: "Namibia".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-400.0, -100.0),
            },
            Country {
                id: 38,
                name: "Niger".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-400.0, 250.0),
            },
            Country {
                id: 39,
                name: "Nigeria".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-380.0, 200.0),
            },
            Country {
                id: 40,
                name: "Rwanda".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-280.0, -100.0),
            },
            Country {
                id: 41,
                name: "Sao Tome and Principe".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-350.0, 0.0),
            },
            Country {
                id: 42,
                name: "Senegal".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-520.0, 250.0),
            },
            Country {
                id: 43,
                name: "Seychelles".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-100.0, -220.0),
            },
            Country {
                id: 44,
                name: "Sierra Leone".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-500.0, 200.0),
            },
            Country {
                id: 45,
                name: "Somalia".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-50.0, 100.0),
            },
            Country {
                id: 46,
                name: "South Africa".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-350.0, -150.0),
            },
            Country {
                id: 47,
                name: "South Sudan".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-200.0, 100.0),
            },
            Country {
                id: 48,
                name: "Sudan".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-250.0, 250.0),
            },
            Country {
                id: 49,
                name: "Tanzania".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-200.0, -50.0),
            },
            Country {
                id: 50,
                name: "Togo".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-380.0, 200.0),
            },
            Country {
                id: 51,
                name: "Tunisia".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-420.0, 300.0),
            },
            Country {
                id: 52,
                name: "Uganda".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-200.0, -50.0),
            },
            Country {
                id: 53,
                name: "Zambia".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-300.0, -100.0),
            },
            Country {
                id: 54,
                name: "Zimbabwe".to_string(),
                continent: Continent::Africa,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-300.0, -100.0),
            },
            // Asia
            Country {
                id: 55,
                name: "Afghanistan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(100.0, 200.0),
            },
            Country {
                id: 56,
                name: "Armenia".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(50.0, 300.0),
            },
            Country {
                id: 57,
                name: "Azerbaijan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(80.0, 300.0),
            },
            Country {
                id: 58,
                name: "Bahrain".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(0.0, 150.0),
            },
            Country {
                id: 59,
                name: "Bangladesh".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(200.0, 150.0),
            },
            Country {
                id: 60,
                name: "Bhutan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(200.0, 200.0),
            },
            Country {
                id: 61,
                name: "Brunei".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(300.0, 0.0),
            },
            Country {
                id: 62,
                name: "Cambodia".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(250.0, 50.0),
            },
            Country {
                id: 63,
                name: "China".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(250.0, 250.0),
            },
            Country {
                id: 64,
                name: "Georgia".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(50.0, 320.0),
            },
            Country {
                id: 65,
                name: "Hong Kong".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(280.0, 200.0),
            },
            Country {
                id: 66,
                name: "India".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(150.0, 100.0),
            },
            Country {
                id: 67,
                name: "Indonesia".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(280.0, -50.0),
            },
            Country {
                id: 68,
                name: "Iran".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(50.0, 200.0),
            },
            Country {
                id: 69,
                name: "Iraq".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(0.0, 200.0),
            },
            Country {
                id: 70,
                name: "Israel".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-50.0, 150.0),
            },
            Country {
                id: 71,
                name: "Japan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(350.0, 300.0),
            },
            Country {
                id: 72,
                name: "Jordan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-40.0, 180.0),
            },
            Country {
                id: 73,
                name: "Kazakhstan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(150.0, 350.0),
            },
            Country {
                id: 74,
                name: "North Korea".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(300.0, 300.0),
            },
            Country {
                id: 75,
                name: "South Korea".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(310.0, 280.0),
            },
            Country {
                id: 76,
                name: "Kuwait".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(0.0, 170.0),
            },
            Country {
                id: 77,
                name: "Kyrgyzstan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(150.0, 280.0),
            },
            Country {
                id: 78,
                name: "Laos".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(230.0, 100.0),
            },
            Country {
                id: 79,
                name: "Lebanon".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-30.0, 200.0),
            },
            Country {
                id: 80,
                name: "Macao".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(280.0, 180.0),
            },
            Country {
                id: 81,
                name: "Malaysia".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(250.0, 50.0),
            },
            Country {
                id: 82,
                name: "Maldives".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(150.0, -50.0),
            },
            Country {
                id: 83,
                name: "Mongolia".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(250.0, 300.0),
            },
            Country {
                id: 84,
                name: "Myanmar".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(200.0, 80.0),
            },
            Country {
                id: 85,
                name: "Nepal".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(180.0, 180.0),
            },
            Country {
                id: 86,
                name: "Oman".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(30.0, 100.0),
            },
            Country {
                id: 87,
                name: "Pakistan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(100.0, 150.0),
            },
            Country {
                id: 88,
                name: "Palestine".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-45.0, 155.0),
            },
            Country {
                id: 89,
                name: "Philippines".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(320.0, 100.0),
            },
            Country {
                id: 90,
                name: "Qatar".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(0.0, 160.0),
            },
            Country {
                id: 91,
                name: "Saudi Arabia".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-20.0, 120.0),
            },
            Country {
                id: 92,
                name: "Singapore".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(260.0, 20.0),
            },
            Country {
                id: 93,
                name: "Sri Lanka".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(180.0, 30.0),
            },
            Country {
                id: 94,
                name: "Syria".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-20.0, 220.0),
            },
            Country {
                id: 95,
                name: "Taiwan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(300.0, 180.0),
            },
            Country {
                id: 96,
                name: "Tajikistan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(140.0, 250.0),
            },
            Country {
                id: 97,
                name: "Thailand".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(230.0, 80.0),
            },
            Country {
                id: 98,
                name: "East Timor".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(320.0, -30.0),
            },
            Country {
                id: 99,
                name: "Turkey".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-10.0, 280.0),
            },
            Country {
                id: 100,
                name: "Turkmenistan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(80.0, 280.0),
            },
            Country {
                id: 101,
                name: "United Arab Emirates".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(20.0, 140.0),
            },
            Country {
                id: 102,
                name: "Uzbekistan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(100.0, 280.0),
            },
            Country {
                id: 103,
                name: "Vietnam".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(250.0, 120.0),
            },
            Country {
                id: 104,
                name: "Yemen".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-30.0, 80.0),
            },
            Country {
                id: 105,
                name: "Thailand".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(230.0, 80.0),
            },
            Country {
                id: 106,
                name: "Timor-Leste".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(330.0, -20.0),
            },
            Country {
                id: 107,
                name: "Tajikistan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(140.0, 250.0),
            },
            Country {
                id: 108,
                name: "Turkmenistan".to_string(),
                continent: Continent::Asia,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(80.0, 280.0),
            },
            // Europe
            Country {
                id: 109,
                name: "Albania".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-100.0, 350.0),
            },
            Country {
                id: 110,
                name: "Andorra".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-200.0, 320.0),
            },
            Country {
                id: 111,
                name: "Austria".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-120.0, 380.0),
            },
            Country {
                id: 112,
                name: "Belarus".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-50.0, 400.0),
            },
            Country {
                id: 113,
                name: "Belgium".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-180.0, 380.0),
            },
            Country {
                id: 114,
                name: "Bosnia and Herzegovina".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-110.0, 360.0),
            },
            Country {
                id: 115,
                name: "Bulgaria".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-80.0, 360.0),
            },
            Country {
                id: 116,
                name: "Croatia".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-120.0, 370.0),
            },
            Country {
                id: 117,
                name: "Cyprus".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-40.0, 320.0),
            },
            Country {
                id: 118,
                name: "Czechia".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-130.0, 390.0),
            },
            Country {
                id: 119,
                name: "Denmark".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-150.0, 400.0),
            },
            Country {
                id: 120,
                name: "Estonia".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-100.0, 420.0),
            },
            Country {
                id: 121,
                name: "Finland".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-80.0, 430.0),
            },
            Country {
                id: 122,
                name: "France".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-200.0, 360.0),
            },
            Country {
                id: 123,
                name: "Germany".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-150.0, 380.0),
            },
            Country {
                id: 124,
                name: "Greece".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-70.0, 340.0),
            },
            Country {
                id: 125,
                name: "Hungary".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-110.0, 380.0),
            },
            Country {
                id: 126,
                name: "Iceland".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-250.0, 420.0),
            },
            Country {
                id: 127,
                name: "Ireland".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-230.0, 380.0),
            },
            Country {
                id: 128,
                name: "Italy".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-150.0, 340.0),
            },
            Country {
                id: 129,
                name: "Kosovo".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-100.0, 355.0),
            },
            Country {
                id: 130,
                name: "Latvia".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-100.0, 410.0),
            },
            Country {
                id: 131,
                name: "Liechtenstein".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-160.0, 380.0),
            },
            Country {
                id: 132,
                name: "Lithuania".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-100.0, 400.0),
            },
            Country {
                id: 133,
                name: "Luxembourg".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-170.0, 375.0),
            },
            Country {
                id: 134,
                name: "Malta".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-170.0, 310.0),
            },
            Country {
                id: 135,
                name: "Moldova".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-60.0, 370.0),
            },
            Country {
                id: 136,
                name: "Monaco".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-190.0, 350.0),
            },
            Country {
                id: 137,
                name: "Montenegro".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-105.0, 355.0),
            },
            Country {
                id: 138,
                name: "Netherlands".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-175.0, 385.0),
            },
            Country {
                id: 139,
                name: "North Macedonia".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-90.0, 360.0),
            },
            Country {
                id: 140,
                name: "Norway".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-160.0, 410.0),
            },
            Country {
                id: 141,
                name: "Poland".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-110.0, 390.0),
            },
            Country {
                id: 142,
                name: "Portugal".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-260.0, 340.0),
            },
            Country {
                id: 143,
                name: "Romania".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-90.0, 370.0),
            },
            Country {
                id: 144,
                name: "Russia".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(0.0, 400.0),
            },
            Country {
                id: 145,
                name: "San Marino".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-160.0, 350.0),
            },
            Country {
                id: 146,
                name: "Serbia".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-105.0, 365.0),
            },
            Country {
                id: 147,
                name: "Slovakia".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-120.0, 385.0),
            },
            Country {
                id: 148,
                name: "Slovenia".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-130.0, 370.0),
            },
            Country {
                id: 149,
                name: "Spain".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-220.0, 320.0),
            },
            Country {
                id: 150,
                name: "Sweden".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-120.0, 420.0),
            },
            Country {
                id: 151,
                name: "Switzerland".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-170.0, 370.0),
            },
            Country {
                id: 152,
                name: "Ukraine".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-70.0, 385.0),
            },
            Country {
                id: 153,
                name: "United Kingdom".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-210.0, 390.0),
            },
            Country {
                id: 154,
                name: "Vatican City".to_string(),
                continent: Continent::Europe,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-160.0, 345.0),
            },
            // North America
            Country {
                id: 155,
                name: "Antigua and Barbuda".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-350.0, 280.0),
            },
            Country {
                id: 156,
                name: "Bahamas".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-320.0, 320.0),
            },
            Country {
                id: 157,
                name: "Barbados".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-340.0, 250.0),
            },
            Country {
                id: 158,
                name: "Belize".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-380.0, 250.0),
            },
            Country {
                id: 159,
                name: "Canada".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-400.0, 350.0),
            },
            Country {
                id: 160,
                name: "Costa Rica".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-400.0, 200.0),
            },
            Country {
                id: 161,
                name: "Cuba".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-350.0, 300.0),
            },
            Country {
                id: 162,
                name: "Dominica".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-345.0, 270.0),
            },
            Country {
                id: 163,
                name: "Dominican Republic".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-340.0, 290.0),
            },
            Country {
                id: 164,
                name: "El Salvador".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-400.0, 220.0),
            },
            Country {
                id: 165,
                name: "Grenada".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-330.0, 240.0),
            },
            Country {
                id: 166,
                name: "Guatemala".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-400.0, 240.0),
            },
            Country {
                id: 167,
                name: "Haiti".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-340.0, 280.0),
            },
            Country {
                id: 168,
                name: "Honduras".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-390.0, 240.0),
            },
            Country {
                id: 169,
                name: "Jamaica".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-350.0, 270.0),
            },
            Country {
                id: 170,
                name: "Mexico".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-400.0, 280.0),
            },
            Country {
                id: 171,
                name: "Nicaragua".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-390.0, 220.0),
            },
            Country {
                id: 172,
                name: "Panama".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-380.0, 180.0),
            },
            Country {
                id: 173,
                name: "Saint Kitts and Nevis".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-350.0, 290.0),
            },
            Country {
                id: 174,
                name: "Saint Lucia".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-345.0, 260.0),
            },
            Country {
                id: 175,
                name: "Saint Vincent and the Grenadines".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-340.0, 250.0),
            },
            Country {
                id: 176,
                name: "Trinidad and Tobago".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-320.0, 200.0),
            },
            Country {
                id: 177,
                name: "United States".to_string(),
                continent: Continent::NorthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-350.0, 350.0),
            },
            // South America
            Country {
                id: 178,
                name: "Argentina".to_string(),
                continent: Continent::SouthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-300.0, -280.0),
            },
            Country {
                id: 179,
                name: "Bolivia".to_string(),
                continent: Continent::SouthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-280.0, -200.0),
            },
            Country {
                id: 180,
                name: "Brazil".to_string(),
                continent: Continent::SouthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-250.0, -150.0),
            },
            Country {
                id: 181,
                name: "Chile".to_string(),
                continent: Continent::SouthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-320.0, -250.0),
            },
            Country {
                id: 182,
                name: "Colombia".to_string(),
                continent: Continent::SouthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-300.0, -50.0),
            },
            Country {
                id: 183,
                name: "Ecuador".to_string(),
                continent: Continent::SouthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-300.0, -100.0),
            },
            Country {
                id: 184,
                name: "Guyana".to_string(),
                continent: Continent::SouthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-250.0, -50.0),
            },
            Country {
                id: 185,
                name: "Paraguay".to_string(),
                continent: Continent::SouthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-280.0, -200.0),
            },
            Country {
                id: 186,
                name: "Peru".to_string(),
                continent: Continent::SouthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-300.0, -150.0),
            },
            Country {
                id: 187,
                name: "Suriname".to_string(),
                continent: Continent::SouthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-240.0, -50.0),
            },
            Country {
                id: 188,
                name: "Uruguay".to_string(),
                continent: Continent::SouthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-290.0, -300.0),
            },
            Country {
                id: 189,
                name: "Venezuela".to_string(),
                continent: Continent::SouthAmerica,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(-280.0, 0.0),
            },
            // Oceania
            Country {
                id: 190,
                name: "Australia".to_string(),
                continent: Continent::Oceania,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(400.0, -200.0),
            },
            Country {
                id: 191,
                name: "Fiji".to_string(),
                continent: Continent::Oceania,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(450.0, -150.0),
            },
            Country {
                id: 192,
                name: "Kiribati".to_string(),
                continent: Continent::Oceania,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(480.0, -100.0),
            },
            Country {
                id: 193,
                name: "Marshall Islands".to_string(),
                continent: Continent::Oceania,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(500.0, -50.0),
            },
            Country {
                id: 194,
                name: "Micronesia".to_string(),
                continent: Continent::Oceania,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(490.0, -80.0),
            },
            Country {
                id: 195,
                name: "Nauru".to_string(),
                continent: Continent::Oceania,
                initial_farming_capacity: 1.0,
                map_position: Vec2::new(485.0, -90.0),
            },
        ];

        CountryDatabase { countries }
    }

    pub fn get_country(&self, id: u16) -> Option<&Country> {
        self.countries.iter().find(|c| c.id == id)
    }
}
